#
# Application Name
#

APPNAME=AccessibleApps

#
# Online Repository Name
#

REPONAME=accessibleapps

#
# Versions
#

QTVERSION=5.11.1
QTVERSIONU=Qt_5_11_1
BUILDENV=msvc2015_64
QTIFWVER=QtIFW-3.0.4

#
# Paths to EXE File
#

COPYFILES=build-CopyFiles-Desktop_${QTVERSIONU}_MSVC2015_64bit-Release/release
CONTACTMANAGER=build-ContactManager-Desktop_${QTVERSIONU}_MSVC2015_64bit-Release/release
EASYNOTEPAD=build-EasyNotepad-Desktop_${QTVERSIONU}_MSVC2015_64bit-Release/release
PARSEWEB=build-ParseWeb-Desktop_${QTVERSIONU}_MSVC2015_64bit-Release/release
ENCRYPTFOLDER=build-EncryptFolder-Desktop_${QTVERSIONU}_MSVC2015_64bit-Release/release
KEYBACKUP=build-KeyBackup-Desktop_${QTVERSIONU}_MSVC2015_64bit-Release/release
#
# Path to QT Files
#

QTHOME=/d/Qt/${QTVERSION}/${BUILDENV}
QTINST=/d/Qt/${QTIFWVER}

