git clone git@github.com:trumpton/EasyNotepad.git
git clone git@github.com:trumpton/ContactManager.git
git clone git@github.com:trumpton/ParseWeb.git
git clone git@github.com:trumpton/EncryptFolder.git
git clone git@github.com:trumpton/Lib.git
git clone git@github.com:trumpton/EncPad.git
git clone git@github.com:trumpton/GoogleFetch.git
git clone git@github.com:trumpton/KeyBackup.git
git clone git@github.com:trumpton/EasyList.git
