#
# Application Name
#

APPNAME=AccessibleApps

#
# Online Repository Name and QT Version
#

REPONAME=accessibleapps
QTVERSION=5.10.1

#
# Paths to EXE File
#

COPYFILES=build-CopyFiles-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
CONTACTMANAGER=build-ContactManager-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
EASYNOTEPAD=build-EasyNotepad-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
PARSEWEB=build-ParseWeb-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
ENCRYPTFOLDER=build-EncryptFolder-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
KEYBACKUP=build-KeyBackup-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
ENCPAD=build-EncPad-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release
GOOGLEFETCH=build-GoogleFetch-Desktop_Qt_5_10_1_MSVC2015_64bit-Release/release

#
# Setup VC
#

VCINSTALLDIR="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC"

#
# Path to QT Files
#

QTHOME=/e/Qt5.10.1/5.10.1/msvc2015_64
QTINST=/e/QtIFW-3.1.0
