#
# Application Name
#

APPNAME=AccessibleApps

#
# Online Repository Name and QT Version
#

REPONAME=accessibleapps
QTVERSION=6.7.3


#
# Paths to EXE File
#

COPYFILES=build/CopyFiles/release
CONTACTMANAGER=build/ContactManager/release
EASYNOTEPAD=build/EasyNotepad/release
PARSEWEB=build/ParseWeb/release
ENCRYPTFOLDER=build/EncryptFolder/release
KEYBACKUP=build/KeyBackup/release
ENCPAD=build/EncPad/release
GOOGLEFETCH=build/GoogleFetch/release

#
# Setup VC
#

VCINSTALLDIR="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC"

#
# Path to QT Files
#

QTHOME=/c/dev/Qt/6.7.3/msvc2019_64
QTINST=/c/dev/Qt/Tools/QtInstallerFramework/4.8
