#
# Application Name
#

APPNAME=AccessibleApps

#
# Online Repository Name
#

REPONAME=accessibleapps

#
# Versions
#

QTVERSION=5.10.1
BUILDENV=msvc2015_64
QTIFWVER=QtIFW-3.0.4

#
# Paths to EXE File
#

COPYFILES=build-CopyFiles-Desktop_Qt_5_10_1_MSVC2015_64bit2-Release/release
CONTACTMANAGER=build-ContactManager-Desktop_Qt_5_10_1_MSVC2015_64bit2-Release/release
EASYNOTEPAD=build-EasyNotepad-Desktop_Qt_5_10_1_MSVC2015_64bit2-Release/release
PARSEWEB=build-ParseWeb-Desktop_Qt_5_10_1_MSVC2015_64bit2-Release/release
ENCRYPTFOLDER=build-EncryptFolder-Desktop_Qt_5_10_1_MSVC2015_64bit2-Release/release

#
# Path to QT Files
#

QTHOME=/d/Qt/${QTVERSION}/${BUILDENV}
QTINST=/d/Qt/${QTIFWVER}

